<a href="https://colab.research.google.com/github/radwaelreedy/ml-data-analysis/blob/main/multiple_linear_regressionAssignment_multiple_linear_regression_Boston.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dt = pd.read_csv('/content/Boston.csv')

In [3]:
dt

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0


In [4]:
dt = dt.drop('Unnamed: 0', axis=1)

In [5]:
dt

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0


In [6]:
dt.shape

(506, 14)

In [7]:
X = dt.iloc[:,0:13].values
y=dt.iloc[:,13].values

In [8]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.4, random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
# sc = StandardScaler()
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
reg = linear_model.LinearRegression()

reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred =reg.predict(X_test)
y_pred

array([28.70025691, 37.27542414, 14.45066349, 25.73435643, 18.49763912,
       22.76561878, 17.11890368, 13.48208813, 22.54968769, 20.55427051,
       24.89964971, 17.95378789, -6.25387186, 21.45751485, 19.24359044,
       25.88484249, 20.03562327,  5.43649759, 40.51846823, 17.25804397,
       27.97547423, 30.52428232, 10.62579589, 24.13957256, 17.9691631 ,
       15.70456146, 23.13185264, 14.47022575, 22.38985994, 19.37080505,
       22.24020037, 25.33048308, 25.11428577, 18.622199  , 16.09804981,
       17.56608944, 30.84772682, 20.52366567, 24.21685764, 25.12389018,
       13.87545879, 32.08576418, 42.69334232, 17.57356292, 27.18664139,
       17.00879858, 13.65816821, 26.32678962, 19.85072475, 30.22451992,
       20.89326788, 34.32273159, 15.30429383, 26.09067695, 39.54965618,
       22.78325442, 18.64595069, 33.48386781, 24.94968103, 12.43100969,
       22.47035481, 30.85432505, 32.1854089 , 16.87897756, 20.67775641,
       16.56514522, 20.02974058, 26.41085611, 31.55334393, 12.01

In [13]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))


0.7125140936111223


In [14]:
reg.score(X_train, y_train)

0.747199884740759

In [15]:
a = reg.coef_
a

array([-10.09760831,   3.60978024,   0.79557132,   3.51131977,
        -7.0233589 ,  18.7108654 ,  -1.74346842, -16.38195487,
         5.81936946,  -5.253767  ,  -8.33224218,   4.27665681,
       -20.87126481])

In [16]:
b = reg.intercept_
b

np.float64(28.008173027118545)

In [17]:
y_pred1= a.dot(X_test.T)+b
y_pred1

array([28.70025691, 37.27542414, 14.45066349, 25.73435643, 18.49763912,
       22.76561878, 17.11890368, 13.48208813, 22.54968769, 20.55427051,
       24.89964971, 17.95378789, -6.25387186, 21.45751485, 19.24359044,
       25.88484249, 20.03562327,  5.43649759, 40.51846823, 17.25804397,
       27.97547423, 30.52428232, 10.62579589, 24.13957256, 17.9691631 ,
       15.70456146, 23.13185264, 14.47022575, 22.38985994, 19.37080505,
       22.24020037, 25.33048308, 25.11428577, 18.622199  , 16.09804981,
       17.56608944, 30.84772682, 20.52366567, 24.21685764, 25.12389018,
       13.87545879, 32.08576418, 42.69334232, 17.57356292, 27.18664139,
       17.00879858, 13.65816821, 26.32678962, 19.85072475, 30.22451992,
       20.89326788, 34.32273159, 15.30429383, 26.09067695, 39.54965618,
       22.78325442, 18.64595069, 33.48386781, 24.94968103, 12.43100969,
       22.47035481, 30.85432505, 32.1854089 , 16.87897756, 20.67775641,
       16.56514522, 20.02974058, 26.41085611, 31.55334393, 12.01